[package]
name = "titanirc-types"
version = "0.1.0"
authors = ["Jordan Doyle <jordan@doyle.la>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paste = "1.0"
nom = "6.1"
derive_more = "0.99"
bytes = "1.0"